version: '3.4'

services: 
    webmvc:
        image: carpool-app:1.0
        ports: 
            - "5000:5000"
        depends_on: 
            - db
    db:
        image: carpool-app-db:1.0
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=#Password3